export const ROUTES = {
  LOGIN:       '/login',
  DASHBOARD:   '/dashboard',
  TASKS:       '/tasks',
  BULLETIN:    '/bulletin',
  NOTES:       '/notes',
  DATABASE:    '/database',
  PROFILE:     '/profile',
  ADMIN_USERS:        '/admin/users',
  ADMIN_DIVISIONS:    '/admin/divisions',
  ADMIN_ROLES:        '/admin/roles',
  ADMIN_PERMISSIONS:  '/admin/permissions',
  ANALYTICS:          '/analytics',
  ADMIN_AUDIT_LOG:    '/admin/audit-log',
  NOTIFICATIONS:      '/notifications',
  WORK_ORDERS:        '/work-orders',
  HRIS:                  '/hris',
  HRIS_ATTENDANCE:       '/hris/attendance',
  HRIS_LEAVE:            '/hris/leave',
  HRIS_OVERTIME:         '/hris/overtime',
  HRIS_REPORTS:          '/hris/reports',
  HRIS_ADMIN_SHIFTS:     '/hris/admin/shifts',
  HRIS_ADMIN_LOCATIONS:  '/hris/admin/locations',
} as const;
